# Generated by Django 3.0.6 on 2020-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20200511_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content2',
        ),
        migrations.AddField(
            model_name='post',
            name='content1',
            field=models.TextField(default='lorem ipsum dolor sit amet'),
        ),
    ]
